In [1]:
import tensorflow as tf
import numpy as np


In [2]:
goal_size = 4
example_goal = np.zeros((goal_size,goal_size))
example_goal = np.random.rand(4,4)
# example_goal[0][0] = 1

np.random.shuffle(example_goal[0])
print(example_goal, '\n', tf.argmax(example_goal))

# np.random.shuffle(example_goal)
example_goal = tf.convert_to_tensor(example_goal)
print(tf.argmax(example_goal, 1), tf.reduce_max(example_goal))
highest_vals_per_col = tf.argmax(example_goal, 1)
print(highest_vals_per_col, highest_vals_per_col.shape)

# max_value = max(example_goal)
# max_index = my_list.index(max_value)

[[0.61088984 0.68103721 0.47308352 0.67269801]
 [0.47186452 0.14230699 0.23361827 0.29765737]
 [0.35578904 0.9154858  0.68585227 0.05905126]
 [0.77246915 0.09668479 0.96035239 0.29426861]] 
 tf.Tensor([3 2 3 0], shape=(4,), dtype=int64)
tf.Tensor([1 0 1 2], shape=(4,), dtype=int64) tf.Tensor(0.9603523859138947, shape=(), dtype=float64)
tf.Tensor([1 0 1 2], shape=(4,), dtype=int64) (4,)


In [3]:
place_h = []
# for i in range(goal_size):
#     print(i, example_goal.shape)
#     a = highest_vals_per_col.data[i]
#     print[a]
#     place_h[i] = [example_goal[0][a]]
    
one_hot_idx = tf.argmax(place_h)
print(one_hot_idx)
one_hot = tf.one_hot(tf.argmax(example_goal), depth=4, dtype=float, on_value=1.0, off_value=0.0)
print(one_hot)
one_hot = tf.squeeze(one_hot)
print(one_hot)


a


InvalidArgumentError: Reduction axis 0 is empty in shape [0] [Op:ArgMax]

In [10]:
a = np.ones((5,5))
a[1][1] = 1

np.random.shuffle(a)
print(a)

padded = np.pad(a, (2, 3))
print(padded)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
