In [34]:
import tensorflow as tf
import numpy as np


In [75]:
goal_size = 4
example_goal = np.zeros((goal_size,goal_size))
example_goal = np.random.rand(4,4)
# example_goal[0][0] = 1

np.random.shuffle(example_goal[0])
print(example_goal, '\n', tf.argmax(example_goal))

# np.random.shuffle(example_goal)
example_goal = tf.convert_to_tensor(example_goal)
print(tf.argmax(example_goal, 1), tf.reduce_max(example_goal))
highest_vals_per_col = tf.argmax(example_goal, 1)
print(highest_vals_per_col, highest_vals_per_col.shape)

# max_value = max(example_goal)
# max_index = my_list.index(max_value)

[[0.97345827 0.60860596 0.77101329 0.28135506]
 [0.19531949 0.86739879 0.43878099 0.69424228]
 [0.16898853 0.76254908 0.05869302 0.0375744 ]
 [0.67791731 0.22029692 0.81170293 0.19097012]] 
 tf.Tensor([0 1 3 1], shape=(4,), dtype=int64)
tf.Tensor([0 1 1 2], shape=(4,), dtype=int64) tf.Tensor(0.9734582655008852, shape=(), dtype=float64)
tf.Tensor([0 1 1 2], shape=(4,), dtype=int64) (4,)


In [64]:
place_h = []
# for i in range(goal_size):
#     print(i, example_goal.shape)
#     a = highest_vals_per_col.data[i]
#     print[a]
#     place_h[i] = [example_goal[0][a]]
    
one_hot_idx = tf.argmax(place_h)
print(one_hot_idx)
one_hot = tf.one_hot(tf.argmax(example_goal), depth=4, dtype=float, on_value=1.0, off_value=0.0)
print(one_hot)
one_hot = tf.squeeze(one_hot)
print(one_hot)


a


0 (4, 4)


TypeError: 'builtin_function_or_method' object is not subscriptable